<a href="https://colab.research.google.com/github/ameerjasser/data-science-toolkit/blob/main/NumPy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[6.0,5.0,4.0],[7.0,6.0,8.0]])
print(b)

[[6. 5. 4.]
 [7. 6. 8.]]


**STATISTICS**

In [4]:
state = np.array([[1,2,3],[4,5,6]])

print(np.min(state))

print(np.max(state))

print(np.sum(state))

print(np.mean(state))

1
6
21
3.5


In [8]:
print(np.max(state, axis=0))  #columns

print(np.max(state, axis=1))  #rows

[4 5 6]
[3 6]


**RECORGANIZING ARRAYS**

In [18]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape(6,1)
print(after)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
after = before.reshape(3,2,1)
print(after)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


**VERTICALLY STACKING VECTORS**

In [24]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


**HORIZONTAL STACK**

In [27]:
print(np.hstack([v1,v2,v1]))

[1 2 3 4 5 6 7 8 1 2 3 4]


In [47]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))


[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [48]:
print((h1>3))  # the elements that greater than 3 and it's will returen a boolean values ## in this example nothing greater than 3 because h1 is zeros

[[False False False False]
 [False False False False]]


In [52]:
x = np.array([1,3,5,7,1,3,4,9,8,6])

print((x>3))

[False False  True  True False False  True  True  True  True]


In [53]:
z = np.array([[1,4,6,8],[3,8,3,9]])
print((x>3))

[False False  True  True False False  True  True  True  True]


In [54]:
print(z[z>3])

[4 6 8 8 9]


you can index with a list in NumPy

In [56]:
array = np.array([1,2,3,4,5,6,7,8,9])
print(array[[1,2,8]])

[2 3 9]


In [57]:
array = np.array([[3,5,3,6,3],[9,45,54,7,3]])
print(np.any(array>5, axis=0))

[ True  True  True  True False]


In [58]:
print(np.all(array>5, axis=0))

[False False False  True False]
