<a href="https://colab.research.google.com/github/ameerjasser/data-science-toolkit/blob/main/reviewPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
x, y = True, False
print(x)
print(y)
print(type(x), x, y, x)

True
False
<class 'bool'> True False True


In [15]:
another_var = "{} {} {}".format(8,5, 45)
print(another_var)
print(type(another_var))

8 5 45
<class 'str'>


In [17]:
print(' Data '.strip())

Data


In [27]:
list = ['amir', 'pop', 15, True, "SOOO GOOD"]
print(list)

['amir', 'pop', 15, True, 'SOOO GOOD']


In [26]:
list.append("Strories")
print(list)

['amir', 'pop', 'Strories', 'Strories']


In [28]:
list.pop(2)
print(list)

['amir', 'pop', True, 'SOOO GOOD']


In [35]:
import numpy as np

x = np.ones((2,2))
print(x)

SyntaxError: invalid syntax (ipython-input-3421529474.py, line 3)

In [37]:
x = np.random.random((3,4))
print(x)

[[0.06312645 0.29980403 0.16221197 0.09830615]
 [0.86264721 0.44992673 0.79298048 0.7486591 ]
 [0.09144951 0.79136928 0.58392439 0.86237821]]


In [39]:
x = np.zeros((2,2))
print(x)

x = np.ones((2,2))
print(x)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [43]:
x = np.random.random((6,3)).T  # Transpose an array

print(x)


[[0.42651396 0.83101454 0.19848278 0.66218355 0.3614685  0.92628891]
 [0.0037224  0.1060364  0.31863679 0.4315401  0.46660958 0.09397512]
 [0.3876379  0.34507849 0.20162816 0.86810136 0.38645356 0.06187166]]


In [54]:
arr_1 = np.random.random((4,4))
arr_2 = np.random.random((4,4))

print(arr_1 * arr_2)

[[3.69595709e-01 5.02220694e-01 7.81910596e-01 8.81730796e-02]
 [7.27621224e-01 2.27579874e-01 2.75988049e-01 2.68789725e-01]
 [6.84894464e-01 9.70668497e-02 1.33297594e-01 4.73522942e-02]
 [5.73744339e-04 8.58464778e-02 1.92477635e-01 3.29209626e-01]]


In [58]:
print(np.dot(arr_1, arr_2))

[[1.79983567 1.65886333 1.61498767 1.07445032]
 [1.57817759 1.40486486 1.64674403 1.32481988]
 [0.85454931 1.33932184 1.15646801 1.04503537]
 [0.62120015 1.0158559  0.53773869 0.45467155]]
