<a href="https://colab.research.google.com/github/ameerjasser/data-science-toolkit/blob/main/W03T03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

array = [[1,1],[1,1]]
print(array)

[[1, 1], [1, 1]]


In [ ]:
import numpy as np

array = np.random.rand(3,4)

print(array)

[[0.08302942 0.89406051 0.01414666 0.1159403 ]
 [0.42804125 0.99092615 0.47038149 0.89847519]
 [0.76432381 0.99177221 0.12081122 0.82537205]]


In [ ]:
import numpy as np

array = np.zeros((3,4))

print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np

array = np.ones((3,4))

print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

array = np.random.rand(6,3)

print(array)

[[0.2033648  0.58540518 0.74465366]
 [0.14399241 0.83564946 0.55304579]
 [0.21134818 0.55577485 0.30871225]
 [0.8886767  0.62395968 0.03358977]
 [0.24537708 0.18756912 0.95116556]
 [0.04352167 0.71595732 0.68010004]]
